### ISSUE TITLE
Error while using less

### ISSUE THREAD

**Issue by YPetremann** [Siilwyn/css-declaration-sorter-atom#39]
Atom simply throw me this error, which occur because of a less syntax :

    CssSyntaxError: <css input>:411:3: Unknown word
    409 | #meter {
    410 | 	.bar { position:absolute; content:""; }
    411 | 	&::before {.bar(); bottom:0; left:7px; }
        | 	            ^
    412 | 	&::after {.bar(); bottom:0; right:7px;}
    413 | }

**Comment by Siilwyn** [comment]
Could you try using version `1.1.0`?

**Comment by YPetremann** [comment]
I have updated to 1.1.0 and still got the same error.
You can try yourself with the sample I gave and setting to Less, the problem here seems to be with evaluation of Less mixins.

```less
#meter {
 	.bar { position:absolute; content:""; }
 	&::before {.bar(); bottom:0; left:7px; }
	&::after {.bar(); bottom:0; right:7px;}
}
```

I looked a bit and I don't know if this working as expected, but It seems that your package still depends on postcss 5.2.17 while it use postcss 6.0.8, maybe because it's what's being used by postcss-less ?
