### ISSUE TITLE
Sorting CSS parsing error. CssSyntaxError ... Unclosed string

### ISSUE THREAD

**Issue by tellkonkle** [Siilwyn/css-declaration-sorter-atom#63]
It looks like the hiccup is content: " "; The white spaced string is intentional and should not result in a parsing error...

![sort-error](https://user-images.githubusercontent.com/18474309/33092215-827f6f46-cec7-11e7-822b-044eca9c7462.jpg)

**Comment by Siilwyn** [comment]
I can not replicate this, can you give more information?

Sorting the following snippet alphabetically with Atom 1.22.1 works:
```css
body {
  clear: both;
  content: " ";
  display: block;
  font-size: 0;
  height: 0;
}
```
