### ISSUE TITLE
Sorting SCSS on Windows does not work properly.

### ISSUE THREAD

**Issue by brndto** [Siilwyn/css-declaration-sorter-atom#76]
Hey, is there any way to ignore the vendor prefixes?
I could potentially write a quick regular expression to sort it, it'd be something like skipping the first two hypens, but only if inbetween webkit, ms, o, or moz as variables currently use the double dash syntax (--variable)
That's my only request at the moment.

**Comment by Siilwyn** [comment]
Hi there @branditodesign excuse me for the late reply.

What is your use-case? The goal of this module is to sort the source CSS which normally does not include prefixes.

**Comment by branditodesign** [comment]
Some how I also missed this issue, and I'm a lot later with my reply so excuse me instead.

My use case was to sort my SCSS which it no longer works with it seems :(

**Comment by Siilwyn** [comment]
It should work with SCSS make sure the syntax is set to SCSS in Atom, do you have an example that does not work?

E.g. I just tried it out with the following snippet, the sorting works for me:
```scss
$font-stack:    Helvetica, sans-serif;
$primary-color: #333;

nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  li { display: inline-block; }

  a {
    display: block;
    padding: 6px 12px;
    text-decoration: none;
  }
}
```

**Comment by branditodesign** [comment]
Here's what I was trying to use it on earlier, this is just one of many examples of where it broke, it does seem to be where SCSS/Sass gets complicated though.

```
@mixin css-triangle($color, $direction, $size: 6px, $position: absolute, $round: false) {
  @include pseudo($pos: $position);
  width: 0;
  height: 0;
  @if $round {
    -webkit-border-radius: 3px;
         border-radius: 3px;
  }
  @if $direction == down {
    border-left: $size solid transparent;
    border-right: $size solid transparent;
    border-top: $size solid $color;
    margin-top: 0 - round($size / 2.5);
  } @else
  if $direction == up {
    border-left: $size solid transparent;
    border-right: $size solid transparent;
    border-bottom: $size solid $color;
    margin-bottom: 0 - round($size / 2.5);
  } @else
  if $direction == right {
    border-top: $size solid transparent;
    border-bottom: $size solid transparent;
    border-left: $size solid $color;
    margin-right: -$size;
  } @else
  if $direction == left {
    border-top: $size solid transparent;
    border-bottom: $size solid transparent;
    border-right: $size solid $color;
    margin-left: -$size;
  }
}
```

**Comment by branditodesign** [comment]
I disabled every community package besides [fonts](https://atom.io/packages/fonts) only leaving the atom pre-packaged ones enabled, still happens on all examples listed in here.

**Comment by Siilwyn** [comment]
Hmm that is odd, if I can't reproduce it it's going to be hard to fix.
What versions are you running?
For me `atom -v` returns:
```
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

And `css-declaration-sorter` is on version `1.2.3`.

**Comment by Siilwyn** [comment]
@branditodesign sorry but that example works fine for me too. :/
Result:
```css
#je-suis {
  align-self: center;
  color: red;
  display: block;
  text-align: left;
  #je-suis2 {
    align-self: center;
    color: red;
    display: block;
    text-align: left;
    
  }
}
```

Does Atom maybe have localization settings (as I recognize some French in there) that could influence this?

**Comment by calebmeyer** [comment]
I'm able to reproduce this on my windows machine as well with the first example.

![repro](https://user-images.githubusercontent.com/3342777/52288159-42101f80-2931-11e9-91c6-e78496f6c69c.gif)

**Comment by Siilwyn** [comment]
I asked around and thanks to @calebmeyer I found this is a Windows issue!

**Comment by Siilwyn** [comment]
Much appreciated, so this is a windows bug!

**Comment by calebmeyer** [comment]
I tried downgrading to 1.2.2 and that made the sort SMACSS and sort Concentric CSS commands reorder the properties in the first ul's block.

Both change it from
```css
  ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }
```
to
```css
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }
```

They don't touch the rest of the file, and I'm not sure if that's intentional. Alphabetical (and therefore default sort) still do nothing.
