### ISSUE TITLE
Toggle on save dropdown doesn't do anything

### ISSUE THREAD

**Issue by mcandre** [Siilwyn/css-declaration-sorter-atom#81]
Fortunately, at least the main css-declaration plugin preferences pane's toggle checkbox does appear to work.

I'm using macOS in case that matters.

**Comment by Siilwyn** [comment]
Do you mean this setting?
![image](https://user-images.githubusercontent.com/5701149/55861591-f53a0680-5b76-11e9-83cd-fac79ae8b9d3.png)

It is working for me, can you try disabling other packages, setting the default sort order to 'alphabetically' & creating a new file with the following:
```css
body {
  z-index: 0;
  opacity: 0;
  border: 0;
}
```

Then hitting save which should result in:
```css
body {
  border: 0;
  opacity: 0;
  z-index: 0;
}
```
